/*
 * Offline Emergency Mesh Communication System
 * Copyright (c) 2024. All rights reserved.
 */

package com.mesh.emergency.data.local.entity

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Dedicated Room entity for Global Chat messages broadcast across the entire mesh network.
 *
 * Key design choices:
 * - [messageId] is a UUID generated by the sender — used for deduplication on all receiving nodes.
 * - No [conversationId] needed — all global messages belong to the single shared room.
 * - [deliveryStatus] is a simple string enum to avoid a complex join with DeliveryStatusEntity.
 */
@Entity(
    tableName = "global_messages",
    indices = [Index(value = ["timestamp"])]
)
data class GlobalMessageEntity(
    @PrimaryKey val messageId: String,
    val senderId: String,
    val senderName: String,
    val content: String,
    val timestamp: Long,
    val createdAt: Long = timestamp,
    val updatedAt: Long = timestamp,
    val edited: Boolean = false,
    val deleted: Boolean = false,
    val deliveryStatus: String = "SENT", // "SENDING" | "SENT" | "DELIVERED" | "QUEUED" | "FAILED"
    val readStatus: String = "READ",
    val syncState: String = "SYNCED",
    val editHistory: List<String> = emptyList(),
    val replyToMessageId: String? = null,
    val replyToSenderName: String? = null,
    val replyToContent: String? = null,
    /**
     * Which transport technology delivered this message.
     * Values: "BLUETOOTH" | "LORA" | "WIFI_DIRECT" | "NFC" | "USB_SERIAL" | "UNKNOWN"
     * Stored as metadata only — no transport-specific logic depends on this field.
     */
    val transportType: String = "UNKNOWN"
)
